/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package counter1.forms;

import counter1.utils.TimeCounter;

/**
 *
 * @author Leya
 */
public class CounterFrame extends javax.swing.JFrame {

    /**
     * Creates new form CounterFrame
     */
    public CounterFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSecond = new javax.swing.JButton();
        btnMinute = new javax.swing.JButton();
        btnHour = new javax.swing.JButton();
        lbResult = new javax.swing.JLabel();
        btnDay = new javax.swing.JButton();
        btnIncrement = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSecond.setText("Last Second");
        btnSecond.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSecondMouseClicked(evt);
            }
        });

        btnMinute.setText("Last Minute ");
        btnMinute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinuteMouseClicked(evt);
            }
        });

        btnHour.setText("Last Hour");
        btnHour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHourMouseClicked(evt);
            }
        });

        lbResult.setText("Result");

        btnDay.setText("Last Day");
        btnDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDayMouseClicked(evt);
            }
        });

        btnIncrement.setText("Increment");
        btnIncrement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIncrementMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMinute)
                        .addGap(18, 18, 18)
                        .addComponent(btnHour)))
                .addGap(18, 18, 18)
                .addComponent(btnDay)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIncrement, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMinute)
                        .addComponent(btnHour)
                        .addComponent(btnDay))
                    .addComponent(btnSecond))
                .addGap(79, 79, 79)
                .addComponent(lbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIncrement, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSecondMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSecondMouseClicked
        lbResult.setText(String.format("%d increments in last second.", TimeCounter.getInstance().getCountInLastSecond()));
    }//GEN-LAST:event_btnSecondMouseClicked

    private void btnMinuteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinuteMouseClicked
        lbResult.setText(String.format("%d increments in last minute.", TimeCounter.getInstance().getCountInLastMinute()));
    }//GEN-LAST:event_btnMinuteMouseClicked

    private void btnHourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHourMouseClicked
        lbResult.setText(String.format("%d increments in last hour.", TimeCounter.getInstance().getCountInLastHour()));
    }//GEN-LAST:event_btnHourMouseClicked

    private void btnIncrementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncrementMouseClicked
        TimeCounter.getInstance().increment();
    }//GEN-LAST:event_btnIncrementMouseClicked

    private void btnDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDayMouseClicked
        lbResult.setText(String.format("%d increments in last day.", TimeCounter.getInstance().getCountInLastDay()));
    }//GEN-LAST:event_btnDayMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDay;
    private javax.swing.JButton btnHour;
    private javax.swing.JButton btnIncrement;
    private javax.swing.JButton btnMinute;
    private javax.swing.JButton btnSecond;
    private javax.swing.JLabel lbResult;
    // End of variables declaration//GEN-END:variables
}
